version: '2'
# define all services
services:
  # our service is called CakePHP ;-)
  cakephp:
    # we want to use the image which is build from our Dockerfile
    build:
      context: .
      dockerfile: Dockerfile
    # apache is running on port 80 but we want to expose this to port 4000 on our local machine
    ports:
      - "80:80"
    # we are depending on the mysql backend
    depends_on:
      - mysql
    # we mount the working dir into the container, handy for development 
    volumes:
      - .:/var/www/html/
    environment:
      - SECURITY_SALT
      - MYSQL_HOST=mysql
      - MYSQL_USERNAME
      - MYSQL_PASSWORD
  mysql:
      # we use the mysql base image, version 5.6.36
      #image: mysql:5.6.39
      build: 
        context: .
        dockerfile: Dockerfile.mysql
      ports:
        - "3030:3006"
      # we mount a datavolume to make sure we don't lose data
      volumes:
        - mysql_data:/var/lib/mysql
      # setting some envvars to create the DB
      environment:
        - MYSQL_ROOT_PASSWORD
        - MYSQL_DATABASE
volumes:
    mysql_data: 